### ISSUE TITLE
Milestone #1 - "First contact"

### ISSUE THREAD

**Issue by ckmjreynolds** [ckmjreynolds/BriskMySQL#1]
There are two main purposes of this milestone:
- [ ] - Establish basic understanding of client-side Swift-NIO.
- [ ] - Establish testing infrastructure, potentially including CI.

Successful completion of this milestone:
- [ ] - Connect, handshake, `SELECT 1` against primary targets.

Primary targets are "MariaDB:latest, MySQL:latest, ProxySQL:latest" at the time of writing:

| Platform | Version |
| -------- | -------- |
| [MariaDB](https://hub.docker.com/_/mariadb) | 10.4.11  |
| [MySQL](https://hub.docker.com/_/mysql) | 8.0.18 |
| [ProxySQL](https://hub.docker.com/r/proxysql/proxysql) | 2.0.8 |

**Comment by ckmjreynolds** [comment]
The developer (DBA by profession) uses ProxySQL in front of a MariaDB Galera cluster. At whatever point a true testing matrix is created, may need to include these specifics.

**Comment by ckmjreynolds** [comment]
Changing this:
- [ ] Connect, handshake, SELECT 1 against primary targets.
To:
- [ ] Connect, handshake, `COM_PING` against primary targets.
- [ ] Compression.
- [ ] SSL.

In order to focus just on "first contact" and better establish testing matrix.
